CREATE TABLE IF NOT EXISTS exercise_uploads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    exercise_type VARCHAR(50) NOT NULL,
    video_path VARCHAR(255) NOT NULL,
    notes TEXT,
    feedback TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 